# This rule is not used by the project k8s-cronjob-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.tutorial.kubebuilder.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-cronjob-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-admin-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/status
  verbs:
  - get
